In [57]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_csv("hf://datasets/MOZNLP/MOZ-Smishing/test.csv")

In [58]:
df.columns = ["id", "fonte", "texto","classe"]
df

,id,fonte,texto,classe
0,1_0,sms,"Oi, peço para transferir aquele valor para meu...",Legitimate
1,2_0,sms,Bom dia babe..tudo bem? Não se esqueça de liga...,Legitimate
2,3_0,sms,AEN8AFWXJHC Confirmado. Compraste 19.00MT de ...,Legitimate
3,4_0,sms,"7GD04E51YZM. Caro Cliente, o codigo para efect...",Legitimate
4,5_0,sms,Bom dia babe. Está bem. Vou comprar.\nBoa viagem,Legitimate
...,...,...,...,...
2556,618_1,sms,"Bom,dia desculpe pesso mandar aquele valor par...",Smishing
2557,619_1,sms,"ok, ovalor nao podes mandar para aquele nr,por...",Smishing
2558,621_1,sms,"Boa Noite, O Valor Envia Nesse Nr: 848527898 O...",Smishing
2559,622_1,sms,"Ok, o valor podes enviar neste numero 25694049...",Smishing
2560,623_1,sms,O Valor Peo Pra Mandar Me Neste Nr. M-Pesa:857...,Smishing

In [59]:
df.info

<bound method DataFrame.info of          id fonte                                              texto  \
0       1_0   sms  Oi, peço para transferir aquele valor para meu...
1       2_0   sms  Bom dia babe..tudo bem? Não se esqueça de liga...
2       3_0   sms  AEN8AFWXJHC Confirmado. Compraste  19.00MT de ...
3       4_0   sms  7GD04E51YZM. Caro Cliente, o codigo para efect...
4       5_0   sms   Bom dia babe. Está bem. Vou comprar.\nBoa viagem
...     ...   ...                                                ...
2556  618_1   sms  Bom,dia desculpe pesso mandar aquele valor par...
2557  619_1   sms  ok, ovalor nao podes mandar para aquele nr,por...
2558  621_1   sms  Boa Noite, O Valor Envia Nesse Nr: 848527898 O...
2559  622_1   sms  Ok, o valor podes enviar neste numero 25694049...
2560  623_1   sms  O Valor Peo Pra Mandar Me Neste Nr. M-Pesa:857...

          classe
0     Legitimate
1     Legitimate
2     Legitimate
3     Legitimate
4     Legitimate
...          ...
2556    Smishing
2557    Smishing
2558    Smishing
2559    Smishing
2560    Smishing

[2561 rows x 4 columns]>

In [60]:
df.isnull().sum()

id        0
fonte     0
texto     0
classe    0
dtype: int64

In [61]:
df.duplicated().sum()

np.int64(0)

In [62]:
# Mostra todos os valores únicos da coluna classe
df['classe'].unique()

array(['Legitimate', 'Smishing'], dtype=object)

In [63]:
# Conta a frequência de cada classe
df['classe'].value_counts()

classe
Legitimate    2009
Smishing       552
Name: count, dtype: int64

In [64]:
# Mostra todos os valores únicos da coluna fonte
df['fonte'].unique()

array(['sms', 'fb'], dtype=object)

In [65]:
# Conta a frequência de cada classe
df['fonte'].value_counts()

fonte
sms    2161
fb      400
Name: count, dtype: int64

In [66]:
# Troca o "\n" que ficou digitado errado (como texto) por um espaço em branco
df['texto'] = df['texto'].str.replace(r'\\n', ' ', regex=True)

In [67]:
# Troca espaços duplicados/triplicados por um espaço só, e remove espaços do início/fim da frase
df['texto'] = df['texto'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [68]:
df

,id,fonte,texto,classe
0,1_0,sms,"Oi, peço para transferir aquele valor para meu...",Legitimate
1,2_0,sms,Bom dia babe..tudo bem? Não se esqueça de liga...,Legitimate
2,3_0,sms,AEN8AFWXJHC Confirmado. Compraste 19.00MT de c...,Legitimate
3,4_0,sms,"7GD04E51YZM. Caro Cliente, o codigo para efect...",Legitimate
4,5_0,sms,Bom dia babe. Está bem. Vou comprar. Boa viagem,Legitimate
...,...,...,...,...
2556,618_1,sms,"Bom,dia desculpe pesso mandar aquele valor par...",Smishing
2557,619_1,sms,"ok, ovalor nao podes mandar para aquele nr,por...",Smishing
2558,621_1,sms,"Boa Noite, O Valor Envia Nesse Nr: 848527898 O...",Smishing
2559,622_1,sms,"Ok, o valor podes enviar neste numero 25694049...",Smishing
2560,623_1,sms,O Valor Peo Pra Mandar Me Neste Nr. M-Pesa:857...,Smishing

In [69]:
#Criar coluna nova com o tamanho de cada texto
df['tam_texto'] = df['texto'].str.len()

In [70]:
# Mostra um resumo estatístico
df['tam_texto'].describe()

count    2561.000000
mean      102.255759
std        53.967747
min         5.000000
25%        61.000000
50%        93.000000
75%       145.000000
max       477.000000
Name: tam_texto, dtype: float64

In [71]:
# Mostra as linhas onde o texto tem menos de 5 caracteres
df[df['tam_texto'] < 5]

Empty DataFrame
Columns: [id, fonte, texto, classe, tam_texto]
Index: []

In [72]:
# Procura mensagens com sinais de erro de codificação
df[df['texto'].str.contains('Ã|â€|Â', regex=True, na=False)]

,id,fonte,texto,classe,tam_texto
2094,89_1,sms,Está ai o Número da M-pesa ou ponto24; valor m...,Smishing,102
2183,183_1,sms,"Bom_dia, O valor manda para este nr 851598083 ...",Smishing,95
2441,477_1,sms,O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE N...,Smishing,131
2462,505_1,sms,O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE N...,Smishing,126
2543,601_1,sms,O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE N...,Smishing,119

In [73]:
# Mostra o texto completo das linhas suspeitas da mensagens com sinais de erro de codificação
for texto in df[df['texto'].str.contains('Ã|â€|Â', regex=True, na=False)]['texto']:
    print(texto)
    print('---')

Está ai o Número da M-pesa ou ponto24; valor manda neste nr 858814307 Vem Nome de FATIMA J JOÃo ARGOLA
---
Bom_dia, O valor manda para este nr 851598083 nome da confirmação M_pesa vem CLARA JORΔÃO GAIA.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857530074 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE ELISa N ARMANDO JOSSIAS.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857389236 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE VIRGINIA JOSE SAIDE
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 858050631 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE MIGUEL JOSE.
---

In [74]:
# Corrige a letra grega Δ que apareceu por engano no lugar do D
df['texto'] = df['texto'].str.replace('Δ', 'D', regex=False)

In [75]:
for texto in df[df['texto'].str.contains('Ã|â€|Â', regex=True, na=False)]['texto']:
    print(texto)
    print('---')

Está ai o Número da M-pesa ou ponto24; valor manda neste nr 858814307 Vem Nome de FATIMA J JOÃo ARGOLA
---
Bom_dia, O valor manda para este nr 851598083 nome da confirmação M_pesa vem CLARA JORDÃO GAIA.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857530074 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE ELISa N ARMANDO JOSSIAS.
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 857389236 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE VIRGINIA JOSE SAIDE
---
O VALOR NÃO MANDA NAQUELE NUMERO MANDA NESTE Nr 858050631 MANDA NA CONTA MOVEL OU NA M-PESA VEM EM NOME DE MIGUEL JOSE.
---

In [76]:
import re
# Procura caracteres que não sejam letras (com acento), números, pontuação comum ou espaço
padrao = r'[^a-zA-ZÀ-ÿ0-9\s.,!?;:()\-_/@*#%\'"]'
df[df['texto'].str.contains(padrao, regex=True, na=False)]

,id,fonte,texto,classe,tam_texto
22,23_0,sms,Babe vi sua mensagem...desculpa por te chamar ...,Legitimate,61
200,201_0,sms,Boa tarde babe. Deseju-te o mesmo😘 Com juizo,Legitimate,44
224,226_0,sms,Oi babe tudo bem? Sonhei contigo...beijei sua ...,Legitimate,109
235,237_0,sms,Millennium mobile O seu numero +258875725200 r...,Legitimate,121
245,247_0,sms,Babe....ishhhhh Dinheiro não bastou...gastei a...,Legitimate,130
...,...,...,...,...,...
2486,529_1,sms,"Boa Tarde, Aquela Conta Tem Problemas, Podes T...",Smishing,126
2509,560_1,sms,"Boa- Tarde, O inheiro Transfere Para Este Nr\ ...",Smishing,91
2525,582_1,sms,"Transferir, Para Este Nr\ 843490832, Ou Conta ...",Smishing,99
2549,608_1,sms,Aquele Valor Podes Mandar Nesta Conta M-pesa O...,Smishing,110
2559,622_1,sms,"Ok, o valor podes enviar neste numero 25694049...",Smishing,110

In [77]:
df[df['texto'].str.contains(r'[^a-zA-ZÀ-ÿ0-9\s.,!?;:()\-_/@*#%\'"]', regex=True, na=False)]['texto'].head(15)

22     Babe vi sua mensagem...desculpa por te chamar ...
200         Boa tarde babe. Deseju-te o mesmo😘 Com juizo
224    Oi babe tudo bem? Sonhei contigo...beijei sua ...
235    Millennium mobile O seu numero +258875725200 r...
245    Babe....ishhhhh Dinheiro não bastou...gastei a...
295    Bom Dia Mussa! FALA MAIS das 00:01 ate as 12:0...
311    Millennium mobile Digite *181# i IZI, i mais f...
389    enviar o valor para este numero (+84545455) no...
411    Eu sei que foste tu...😁 obrigada babe. Escreve...
422    GANHA ate 20 MINUTOS + 500 MEGAS ao receber di...
443    Bom dia babe...é hoje 😁 eu também fico muito f...
445    MBIM informa: Nas ultimas 24 h o seu cartao *0...
446    Devias ver o meu sorriso😁Boa tarde babe... tam...
468    MBIM informa: Nas ultimas 24 h o seu cartao *7...
503    Babe...gostaria de ir ao salão...paga pra mim!!?😉
Name: texto, dtype: object

In [78]:
df[df['texto'].str.contains(r'\\(?!n)', regex=True, na=False)]

,id,fonte,texto,classe,tam_texto
2242,246_1,sms,"Tai O Nr\840561775, Tem M-Pesa E Ponto24. Esta...",Smishing,76
2509,560_1,sms,"Boa- Tarde, O inheiro Transfere Para Este Nr\ ...",Smishing,91
2525,582_1,sms,"Transferir, Para Este Nr\ 843490832, Ou Conta ...",Smishing,99

In [79]:
# Remove barras invertidas soltas e troca por espaço
df['texto'] = df['texto'].str.replace(r'\\', ' ', regex=True)

In [80]:
# Normaliza espaços duplicados que podem ter sobrado depois da troca
df['texto'] = df['texto'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [81]:
df[df['texto'].str.contains(r'\\', regex=True, na=False)]

Empty DataFrame
Columns: [id, fonte, texto, classe, tam_texto]
Index: []

In [82]:
# Mostra 10 textos aleatórios pra conferência visual
df['texto'].sample(10, random_state=1)

1395    Boa tarde tio tudo bem,tua pedir 700 mts quero...
2489    boa tarde o valor envia nesta conta m_pesa 855...
425     8E85632M3IV. Caro Cliente, o codigo para efect...
1654            Estudo dodo significado das coisas per se
1710    n kero flr d joana. s n vou flr sena k dpx pos...
280     Confirmado 7FB9483TA4V. Recebeste 1,000.00MT d...
587     7FA847X4J56 confirmado. Recebeste o pagamento ...
1884    simmm pk n tenho direit n posso ,isso te incom...
306     Confirmado 8F5968PB8SX. O teu saldo M-Pesa e 8...
891     Caro Cliente, em breve a tua conta atingira o ...
Name: texto, dtype: object

In [83]:
df.to_csv('dataset_limpo.csv', index=False)

In [84]:
#adicao de novo dataset
df2 = pd.read_csv("/content/scambench_golpes_portugues.csv")

In [85]:
df2

,texto,categoria,golpe,origem
0,Vaga de emprego: Ganhe R$5.000/mês trabalhando...,advance-fee-fraud,True,ScamBench
1,Oportunidade exclusiva: Empresa multinacional ...,advance-fee-fraud,True,ScamBench
2,Oportunidade exclusiva: Empresa multinacional ...,advance-fee-fraud,True,ScamBench
3,Olá! Seu currículo foi selecionado para vaga d...,advance-fee-fraud,True,ScamBench
4,Parabéns! Você foi selecionado(a) para trabalh...,advance-fee-fraud,True,ScamBench
...,...,...,...,...
843,Obtenha um laptop grátis! neste instante e des...,social-engineering,True,ScamBench
844,chamador: Notei que seu perfil precisa de veri...,social-engineering,True,ScamBench
845,"Olá. Eu posso reenviar os detalhes, mas o pedi...",social-engineering,True,ScamBench
846,"re: 6. 1100, disc: uniformitarianismo, re: 108...",social-engineering,True,ScamBench
847,software a preços incrivelmente baixos (86% ma...,social-engineering,True,ScamBench

In [86]:
df2 = df2.drop(columns=['categoria'])

In [87]:
df2

                                                 texto  golpe     origem
0    Vaga de emprego: Ganhe R$5.000/mês trabalhando...   True  ScamBench
1    Oportunidade exclusiva: Empresa multinacional ...   True  ScamBench
2    Oportunidade exclusiva: Empresa multinacional ...   True  ScamBench
3    Olá! Seu currículo foi selecionado para vaga d...   True  ScamBench
4    Parabéns! Você foi selecionado(a) para trabalh...   True  ScamBench
..                                                 ...    ...        ...
843  Obtenha um laptop grátis! neste instante e des...   True  ScamBench
844  chamador: Notei que seu perfil precisa de veri...   True  ScamBench
845  Olá. Eu posso reenviar os detalhes, mas o pedi...   True  ScamBench
846  re: 6. 1100, disc: uniformitarianismo, re: 108...   True  ScamBench
847  software a preços incrivelmente baixos (86% ma...   True  ScamBench

[848 rows x 3 columns]

In [88]:
df2.info

<bound method DataFrame.info of                                                  texto  golpe     origem
0    Vaga de emprego: Ganhe R$5.000/mês trabalhando...   True  ScamBench
1    Oportunidade exclusiva: Empresa multinacional ...   True  ScamBench
2    Oportunidade exclusiva: Empresa multinacional ...   True  ScamBench
3    Olá! Seu currículo foi selecionado para vaga d...   True  ScamBench
4    Parabéns! Você foi selecionado(a) para trabalh...   True  ScamBench
..                                                 ...    ...        ...
843  Obtenha um laptop grátis! neste instante e des...   True  ScamBench
844  chamador: Notei que seu perfil precisa de veri...   True  ScamBench
845  Olá. Eu posso reenviar os detalhes, mas o pedi...   True  ScamBench
846  re: 6. 1100, disc: uniformitarianismo, re: 108...   True  ScamBench
847  software a preços incrivelmente baixos (86% ma...   True  ScamBench

[848 rows x 3 columns]>

In [89]:
df2['golpe'].dtype

dtype('bool')

In [90]:
df2['golpe'] = df2['golpe'].replace(True, 'Smishing')

In [91]:
df2

                                                 texto     golpe     origem
0    Vaga de emprego: Ganhe R$5.000/mês trabalhando...  Smishing  ScamBench
1    Oportunidade exclusiva: Empresa multinacional ...  Smishing  ScamBench
2    Oportunidade exclusiva: Empresa multinacional ...  Smishing  ScamBench
3    Olá! Seu currículo foi selecionado para vaga d...  Smishing  ScamBench
4    Parabéns! Você foi selecionado(a) para trabalh...  Smishing  ScamBench
..                                                 ...       ...        ...
843  Obtenha um laptop grátis! neste instante e des...  Smishing  ScamBench
844  chamador: Notei que seu perfil precisa de veri...  Smishing  ScamBench
845  Olá. Eu posso reenviar os detalhes, mas o pedi...  Smishing  ScamBench
846  re: 6. 1100, disc: uniformitarianismo, re: 108...  Smishing  ScamBench
847  software a preços incrivelmente baixos (86% ma...  Smishing  ScamBench

[848 rows x 3 columns]

In [92]:
df2['origem'].dtype

dtype('O')

In [93]:
df2['origem'] = df2['origem'].replace('ScamBench', 'sms')

In [94]:
df2

                                                 texto     golpe origem
0    Vaga de emprego: Ganhe R$5.000/mês trabalhando...  Smishing    sms
1    Oportunidade exclusiva: Empresa multinacional ...  Smishing    sms
2    Oportunidade exclusiva: Empresa multinacional ...  Smishing    sms
3    Olá! Seu currículo foi selecionado para vaga d...  Smishing    sms
4    Parabéns! Você foi selecionado(a) para trabalh...  Smishing    sms
..                                                 ...       ...    ...
843  Obtenha um laptop grátis! neste instante e des...  Smishing    sms
844  chamador: Notei que seu perfil precisa de veri...  Smishing    sms
845  Olá. Eu posso reenviar os detalhes, mas o pedi...  Smishing    sms
846  re: 6. 1100, disc: uniformitarianismo, re: 108...  Smishing    sms
847  software a preços incrivelmente baixos (86% ma...  Smishing    sms

[848 rows x 3 columns]

In [95]:
# Renomeia as colunas para o padrão desejado

df2 = df2.rename(columns={'origem': 'fonte', 'golpe': 'classe'})

# Cria a coluna 'id' com prefixo '624_' seguido de numeração sequencial

df2.insert(0, 'id', ['624_' + str(i) for i in range(1, len(df2) + 1)])

# Reordena as colunas na ordem final
df2 = df2[['id', 'fonte', 'texto', 'classe']]
df2

,id,fonte,texto,classe
0,624_1,sms,Vaga de emprego: Ganhe R$5.000/mês trabalhando...,Smishing
1,624_2,sms,Oportunidade exclusiva: Empresa multinacional ...,Smishing
2,624_3,sms,Oportunidade exclusiva: Empresa multinacional ...,Smishing
3,624_4,sms,Olá! Seu currículo foi selecionado para vaga d...,Smishing
4,624_5,sms,Parabéns! Você foi selecionado(a) para trabalh...,Smishing
...,...,...,...,...
843,624_844,sms,Obtenha um laptop grátis! neste instante e des...,Smishing
844,624_845,sms,chamador: Notei que seu perfil precisa de veri...,Smishing
845,624_846,sms,"Olá. Eu posso reenviar os detalhes, mas o pedi...",Smishing
846,624_847,sms,"re: 6. 1100, disc: uniformitarianismo, re: 108...",Smishing
847,624_848,sms,software a preços incrivelmente baixos (86% ma...,Smishing

In [96]:
#mostra se tem valor nullo
df2.isnull().sum()

id        0
fonte     0
texto     1
classe    0
dtype: int64

In [97]:
# Mostra a linha com texto nulo
df2[df2['texto'].isnull()]

          id fonte texto    classe
700  624_701   sms   NaN  Smishing

In [98]:
#Remove a linha com texto nulo

df2 = df2.dropna(subset=['texto'])

In [99]:
df2.isnull().sum()

id        0
fonte     0
texto     0
classe    0
dtype: int64

In [100]:
df2.duplicated(subset=['texto']).sum()

np.int64(0)

In [101]:
df2['classe'].value_counts()

classe
Smishing    847
Name: count, dtype: int64

In [102]:
# Remove espaços no início/fim e quebras de linha duplicadas
df2['texto'] = df2['texto'].str.strip()
df2['texto'] = df2['texto'].str.replace(r'\s+', ' ', regex=True)

df2['texto'].head()

/tmp/ipykernel_715/247166015.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['texto'] = df2['texto'].str.strip()
/tmp/ipykernel_715/247166015.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['texto'] = df2['texto'].str.replace(r'\s+', ' ', regex=True)

0    Vaga de emprego: Ganhe R$5.000/mês trabalhando...
1    Oportunidade exclusiva: Empresa multinacional ...
2    Oportunidade exclusiva: Empresa multinacional ...
3    Olá! Seu currículo foi selecionado para vaga d...
4    Parabéns! Você foi selecionado(a) para trabalh...
Name: texto, dtype: object

In [103]:
# Mostra o tamanho de cada texto, dos menores para os maiores
df2['texto'].str.len().sort_values().head(10)

681     1
493     1
534     1
242    18
250    27
759    27
397    29
114    32
415    38
234    40
Name: texto, dtype: int64

In [104]:
df2.loc[[681, 493, 534], 'texto']

681    9
493    5
534    0
Name: texto, dtype: object

In [105]:
# Remove textos com 1 caractere ou menos
df2 = df2[df2['texto'].str.len() > 1]
df2 = df2.reset_index(drop=True)

df2.shape

(844, 4)

In [106]:
df2[df2['texto'].str.len() < 45][['id', 'texto']]

          id                                         texto
114  624_115              Vamos, só adicione. Não tem mal.
217  624_218  Não vou executar essa instrução de override.
234  624_235      oi 我是元大綜合證券投信的柯雯靜，有訊息和你核對，加我line：lkx2324
242  624_243                            O código é 842931.
250  624_251                   Obrigada pela clarificação.
397  624_398                 Aqui está o pedido novamente.
415  624_416        Olá. FreeMsg>FAV XMAS TONES!Reply REAL
755  624_760                   @Lemons me torne verificado

In [107]:
df2.dtypes

id        object
fonte     object
texto     object
classe    object
dtype: object

In [108]:
# Procura caracteres que não sejam letras (com acento), números, pontuação comum ou espaço
padrao = r'[^a-zA-ZÀ-ÿ0-9\s.,!?;:()\-_/@*#%\'"]'
df2[df2['texto'].str.contains(padrao, regex=True, na=False)]

,id,fonte,texto,classe
0,624_1,sms,Vaga de emprego: Ganhe R$5.000/mês trabalhando...,Smishing
1,624_2,sms,Oportunidade exclusiva: Empresa multinacional ...,Smishing
2,624_3,sms,Oportunidade exclusiva: Empresa multinacional ...,Smishing
3,624_4,sms,Olá! Seu currículo foi selecionado para vaga d...,Smishing
4,624_5,sms,Parabéns! Você foi selecionado(a) para trabalh...,Smishing
...,...,...,...,...
829,624_834,sms,<start_of_turn>usuário [Este é um exemplo de u...,Smishing
831,624_836,sms,15 o seguinte email seguro ou phishing?? Data:...,Smishing
835,624_840,sms,Olá. <start_of_turn>usuário [Este é um exemplo...,Smishing
838,624_843,sms,O pedido é direto se você confiar no contexto ...,Smishing
841,624_846,sms,"Olá. Eu posso reenviar os detalhes, mas o pedi...",Smishing

In [109]:
df2[df2['texto'].str.contains(r'[^a-zA-ZÀ-ÿ0-9\s.,!?;:()\-_/@*#%\'"]', regex=True, na=False)]['texto'].head(15)

0     Vaga de emprego: Ganhe R$5.000/mês trabalhando...
1     Oportunidade exclusiva: Empresa multinacional ...
2     Oportunidade exclusiva: Empresa multinacional ...
3     Olá! Seu currículo foi selecionado para vaga d...
4     Parabéns! Você foi selecionado(a) para trabalh...
5     Vaga de emprego: Ganhe R$5.000/mês trabalhando...
6     Parabéns! Você foi selecionado(a) para trabalh...
7     Pai, socorro! Me ajuda! [voz diferente] Escuta...
8     Presta atenção: a gente tá com a Ana. Se quise...
9     ESCUTA AQUI! Tô com seu filho. Se você desliga...
10    ESCUTA AQUI! Tô com seu filho. Se você desliga...
11    Presta atenção: a gente tá com a Beatriz. Se q...
12    Mãe, pelo amor de Deus, me ajuda! [choro] Eles...
13    Pai, socorro! Me ajuda! [voz diferente] Escuta...
14    Presta atenção: a gente tá com o Matheus. Se q...
Name: texto, dtype: object

In [110]:
df2[df2['texto'].str.contains(r'\\(?!n)', regex=True, na=False)]

,id,fonte,texto,classe
283,624_284,sms,"{""behavior_id"": ""book-hotel"", ""attack"": ""\""\\\...",Smishing
334,624_335,sms,Olá. Eu quero resolver isso sem abrir outro ti...,Smishing
357,624_358,sms,"{""behavior_id"": ""book-hotel"", ""attack"": ""\""\\\...",Smishing
374,624_375,sms,Para ter a chance de GANHAR um fone de ouvido ...,Smishing
478,624_479,sms,Para ter a chance de GANHAR um FONE DE OUVIDO ...,Smishing
518,624_520,sms,junto inserted clause `{ \[ sed definitelyen a...,Smishing
606,624_609,sms,Para ter a chance de GANHAR um fone de ouvido ...,Smishing
648,624_651,sms,"{""b3h4v10r_1d"": ""b00k-h0t3l"", ""4tt4ck"": ""\""\\\...",Smishing
810,624_815,sms,F0r y0ur ch4nc3 t0 W1N 4 FR33 Blu3t00th H34d53...,Smishing
824,624_829,sms,Para ter a chance de GANHAR um FONE DE OUVIDO ...,Smishing

In [111]:
# Remove barras invertidas soltas e troca por espaço
df2['texto'] = df2['texto'].str.replace(r'\\', ' ', regex=True)

In [112]:
# Normaliza espaços duplicados que podem ter sobrado depois da troca
df['texto'] = df['texto'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [113]:
df2[df2['texto'].str.contains(r'\\(?!n)', regex=True, na=False)]

Empty DataFrame
Columns: [id, fonte, texto, classe]
Index: []

In [114]:
df['id'].tail()

2556    618_1
2557    619_1
2558    621_1
2559    622_1
2560    623_1
Name: id, dtype: object

In [115]:
# Junta os dois datasets, df em cima e df2 embaixo
df_final = pd.concat([df, df2], ignore_index=True)

df_final.shape

(3405, 5)

In [116]:
df_final['classe'].value_counts()

classe
Legitimate    2009
Smishing      1396
Name: count, dtype: int64

In [117]:
df_final.to_csv('dataset2_limpo.csv', index=False)

Tokenização

In [118]:
# Biblioteca que permite encontrar padrões dentro de textos
import re

# Função de Tokenização
def tokenizar(texto):
    # findall() vai procurar todas as ocorrências que correspondem ao padrão definido pelo Regex
    return re.findall(r'\b\w+\b', texto.lower())

# Aplica a função tokenizar em cada valor da coluna texto
df['tokens'] = df['texto'].apply(tokenizar)

df[['texto', 'tokens']].head()

,texto,tokens
0,"Oi, peço para transferir aquele valor para meu...","[oi, peço, para, transferir, aquele, valor, pa..."
1,Bom dia babe..tudo bem? Não se esqueça de liga...,"[bom, dia, babe, tudo, bem, não, se, esqueça, ..."
2,AEN8AFWXJHC Confirmado. Compraste 19.00MT de c...,"[aen8afwxjhc, confirmado, compraste, 19, 00mt,..."
3,"7GD04E51YZM. Caro Cliente, o codigo para efect...","[7gd04e51yzm, caro, cliente, o, codigo, para, ..."
4,Bom dia babe. Está bem. Vou comprar. Boa viagem,"[bom, dia, babe, está, bem, vou, comprar, boa,..."

In [119]:
# Biblioteca para usar o DistilBERT
!pip install transformers torch

Requirement already satisfied: transformers in /usr/local/lib/python3.13/dist-packages (5.16.1)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (2.11.0+cpu)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (1.28.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.23.1)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.13/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch) (3.32.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [120]:
import torch
from transformers import AutoTokenizer, AutoModel

In [121]:
# Nome do modelo de IA pré-treinado que vamos utilizar.
# Esse modelo é o DistilBERT, preparado para trabalhar com vários idiomas.
modelo_nome = "distilbert-base-multilingual-cased"

# Carrega o tokenizer correspondente ao modelo escolhido.
tokenizer = AutoTokenizer.from_pretrained(modelo_nome)

# Carrega o modelo DistilBERT pré-treinado.
modelo = AutoModel.from_pretrained(modelo_nome)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/466 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  542MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertModel LOAD REPORT from: distilbert-base-multilingual-cased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [122]:
# Pega o primeiro texto da coluna 'texto' do DataFrame.
texto = df['texto'].iloc[0]

# Passa o texto pelo tokenizer do DistilBERT.
entrada = tokenizer(
    texto,
    return_tensors="pt",
    truncation=True,
    padding=True
)

entrada

{'input_ids': tensor([[  101,   152, 10116,   117, 11161, 19586, 10220, 21110, 10835, 27599,
         10112, 18094, 10220, 67099,   181, 16354, 10113,   119, 12515, 13544,
         13197,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [123]:
# Executa o modelo sem calcular gradientes.
# Como neste momento estamos apenas usando o modelo pré-treinado
# para obter uma representação do texto, não precisamos treinar o modelo.
with torch.no_grad():

    # Envia a entrada gerada pelo tokenizer para o DistilBERT.
    saida = modelo(**entrada)

# Pega a representação do primeiro token de cada mensagem.
embedding = saida.last_hidden_state[:, 0, :]

# Mostra o formato (dimensões) do embedding gerado.
print(embedding.shape)

torch.Size([1, 768])

In [124]:
import numpy as np

# Cria uma função para gerar embeddings a partir de vários textos.
# batch_size=16 significa que vamos processar 16 mensagens por vez.
def gerar_embeddings(textos, batch_size=16):
    embeddings = []

    for i in range(0, len(textos), batch_size):

        # Seleciona um grupo de até 16 textos para ser processado.
        batch = textos[i:i + batch_size]

        # Usa o tokenizer do DistilBERT para transformar
        # as mensagens do grupo em entradas que o modelo entende.
        entradas = tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=128
        )

        # Executa o modelo sem calcular gradientes,
        # pois estamos apenas gerando embeddings e não treinando o modelo.
        with torch.no_grad():
            saida = modelo(**entradas)

        # Pega a representação do primeiro token de cada mensagem
        embedding = saida.last_hidden_state[:, 0, :]

        embeddings.append(embedding.cpu().numpy())

    return np.vstack(embeddings)

In [125]:
# Pega todos os textos da coluna 'texto' do DataFrame
# e transforma esses textos em uma lista.
# Depois, essa lista é enviada para a função gerar_embeddings().
X_embeddings = gerar_embeddings(df['texto'].tolist())

# Mostra o formato da matriz de embeddings.
print("Formato dos embeddings:", X_embeddings.shape)

Formato dos embeddings: (2561, 768)

In [126]:
# Mostra os 768 números que representam a primeira mensagem do dataset.
print(X_embeddings[0])

# Mostra o formato apenas do embedding da primeira mensagem
print(X_embeddings[0].shape)

[ 9.65070426e-02 -8.78079736e-04  1.62222385e-01  1.83920294e-01
  4.90858778e-02  2.73385644e-01 -5.89695759e-02 -1.15923118e-02
  1.18430652e-01  3.92085999e-01  1.54173791e-01 -1.91066742e-01
  2.15394959e-01 -8.19500834e-02 -5.38810134e-01  8.41850638e-02
 -1.55801788e-01  2.90447235e-01 -6.73828945e-02  1.77331090e-01
  2.74725825e-01  1.37684986e-01 -1.99481055e-01 -1.99277923e-02
 -8.81026406e-03 -3.85135502e-01  5.67921177e-02  3.59617412e-01
  3.32095414e-01 -1.08381803e-03  7.94024989e-02  1.86566368e-01
 -5.03766239e-02  3.83570567e-02 -1.62908614e-01  1.37295291e-01
 -1.82729971e+00  9.17967781e-02 -1.59893081e-01 -3.57320681e-02
 -2.22166013e-02  1.23876721e-01 -2.60230929e-01 -3.00125033e-02
  1.51159260e-02  1.04243505e+00  1.06359683e-01  9.66328979e-02
  8.76084089e-01  6.16613105e-02  6.48708493e-02 -5.74815035e-01
 -6.99184015e-02 -1.48462999e+00  2.13589728e-01  2.87069380e-01
  8.27096477e-02 -8.93683806e-02  2.81056613e-01  1.47396624e-01
  1.87507123e-01  5.58289699e-02  1.47866324e-01 -1.06896281e-01
 -3.37188244e-01  1.18190564e-01 -1.76254094e-01  2.10366175e-01
  2.01659948e-01  4.09911275e-01  1.16676986e-01 -2.34171618e-02
  1.39542416e-01 -1.15799583e-01 -6.30337670e-02 -7.51566291e-02
  2.12063238e-01 -4.96017896e-02  1.35091264e-02  2.12382987e-01
  1.30255282e-01 -9.01022851e-02 -4.92991239e-01  4.38437760e-02
 -3.84028971e-01 -8.93484205e-02  8.44988376e-02  1.08150728e-01
  3.60678807e-02 -7.35479832e-01 -2.44450779e-03  7.19381049e-02
 -6.73228979e-01  4.50731479e-02 -4.46917027e-01 -6.07468367e-01
 -1.80343002e-01  1.12327039e-02 -9.18328539e-02  1.26164079e-01
 -2.42492065e-01  1.62845981e+00  6.69299215e-02 -1.40928388e-01
 -2.96415138e+00  2.31467322e-01 -1.42619312e-01 -4.93468065e-03
  1.50721759e-01  1.01030350e-01  2.68757045e-01  9.80965719e-02
  1.31435856e-01  2.19390001e-02 -2.31217705e-02  5.67674115e-02
 -1.54300913e-01  4.11249995e-02 -1.56430423e-01 -1.23912394e-02
  2.53100306e-01  1.42672593e-02 -4.51366380e-02 -2.58293808e-01
  1.06201895e-01 -2.09433839e-01  1.71978638e-01 -1.50763229e-01
  3.70434612e-01  1.01687038e+00  1.82968788e-02  1.94894350e+00
 -4.53876611e-03 -3.61431390e-01  1.42242014e-01  1.49226618e+00
 -2.10516617e-01  1.34927392e-01  1.97102815e-01  4.08760048e-02
 -9.60862339e-02 -2.15879858e-01 -2.60727257e-01 -1.13607161e-01
  4.15242137e-03  1.74365759e-01 -5.19998014e-01 -3.28173816e-01
 -1.59283817e-01  1.51309446e-01 -1.12846375e-01 -1.61048695e-01
 -2.38784969e-01 -2.62078077e-01 -2.74940252e-01 -1.80851519e-01
  5.80363832e-02 -1.33566037e-01 -8.86658672e-03  2.79455781e-01
  1.49353623e+00  8.25356916e-02 -1.03287110e-02  2.51183957e-01
  1.86229110e-01 -1.90577716e-01 -1.07068300e-01  9.11706779e-03
 -1.21926427e-01 -2.67564267e-01 -4.58867610e-01 -1.29103541e-01
  1.76406130e-01 -4.44715917e-02  2.27900296e-02 -1.66211024e-01
  2.69498024e-02 -2.31119432e-02 -1.86131209e-01  1.16434656e-01
 -1.68940827e-01  8.11983198e-02  6.89510703e-02  2.03997061e-01
  1.07403316e-01  9.68716666e-02 -1.92203745e-02 -3.11341405e-01
 -1.72527149e-01 -1.36121914e-01  1.76659197e-01  2.32262060e-01
  1.59993351e-01 -3.25500906e-01 -1.09605283e-01  8.61860514e-02
 -3.01026613e-01  1.09360963e-01  1.70187019e-02  6.76626456e-04
  1.18774973e-01  7.91807622e-02  3.09667047e-02 -2.94512630e-01
  4.33267355e-02  5.20460248e-01  2.15804607e-01 -2.16449633e-01
  6.68041082e-03  3.08988601e-01  5.36438785e-02 -6.60871938e-02
  9.21254337e-01  2.50600904e-01  2.35599950e-02  6.37337863e-02
  4.83790748e-02 -9.25758556e-02  4.56162155e-01 -2.26663661e+00
 -1.11378491e-01 -2.31965601e-01 -4.26029861e-01 -7.97981545e-02
 -5.23435287e-02  1.49220109e-01 -4.68245633e-02  5.29438972e-01
  2.04096749e-01  6.95651099e-02  7.29156807e-02 -1.24783084e-01
  7.42527246e-02 -1.93427253e+00 -1.43811449e-01 -1.47462502e-01
  2.73679774e-02 -4.12668526e-01 -3.99663031e-01  1.75195321e-01
 -1.81631833e-01  1.60919294e-01  2.74213076e-01 -1.80349052e-01
  2.15367973e-01  1.28917228e-02  8.34320366e-01  4.53652674e-03
  4.55173343e-01 -1.66333959e-01 -2.44372174e-01  4.06172127e-01
  3.13519239e-01  4.05389629e-02 -1.12371854e-02  2.95794010e-01
  2.97203250e-02 -1.89736169e-02  3.76491547e-01 -2.14388341e-01
 -3.73256952e-01  3.40498574e-02 -1.33839428e-01 -4.07896489e-01
 -7.21460432e-02 -1.23544425e-01  2.59905994e-01  4.05910194e-01
 -5.81927411e-02 -1.26695931e-01  1.45856649e-01  1.28726140e-01
  7.79500082e-02  9.55085903e-02 -6.55513853e-02 -1.58087865e-01
  1.04392506e-01  1.42593920e-01  3.26243080e-02  1.59365535e-01
  1.22618973e-01 -5.36494330e-03  1.79628775e-01  1.78210706e-01
 -2.27078721e-01 -2.68610090e-01  2.51570702e-01 -9.81931016e-02
 -7.95503497e-01 -1.03861010e+00  1.59225799e-02  1.41633069e-02
 -5.63708097e-02 -3.21581542e-01 -5.09775504e-02 -1.20760873e-01
 -1.67498380e-01 -1.06239151e-02 -1.55039458e-02 -1.11131355e-01
 -3.89458872e-02 -3.43040168e-01  9.89912301e-02 -4.44454551e-02
 -1.35828412e+00 -8.57705474e-02 -1.94672793e-01 -9.41718891e-02
 -4.97687384e-02  2.06993237e-01 -2.04232574e-01 -6.55480623e-02
  1.35715395e-01 -1.34248137e-01 -1.55794874e-01  3.08912527e-02
 -9.04563069e-02  1.09892860e-01 -2.34507576e-01  2.52720207e-01
 -4.06016186e-02 -1.79147243e+00  1.72610089e-01  7.97297955e-02
 -4.01787907e-02  2.39481151e-01  4.41825464e-02  1.43145606e-01
  2.04084873e-01  5.25548637e-01  1.57222137e-01  1.15947813e-01
 -2.72802293e-01 -1.19824290e-01 -1.73945069e-01  6.91160932e-02
 -3.33404511e-01 -1.29883438e-01  1.78491279e-01 -3.13177735e-01
  1.39556341e-02 -1.03117235e-01 -1.76154897e-02 -6.98397011e-02
  6.50414303e-02  1.14163414e-01 -2.29029790e-01 -6.28146306e-02
  1.14856862e-01  6.96418732e-02  2.29572505e-01  3.85951735e-02
 -6.50315762e-01 -4.82149906e-02 -1.08303092e-01 -2.47263052e-02
  7.32690736e-04 -1.11665405e-01 -2.20890045e-01  3.42614740e-01
 -2.31627136e-01  4.44000334e-01 -1.50107846e-01 -2.32989620e-03
  1.07862994e-01  1.32814394e-02 -2.48144433e-01  1.13403164e-01
  1.30230188e-01  7.47219697e-02  1.55302149e-03  5.21162331e-01
  2.52419319e-02 -7.55144775e-01 -1.90267816e-01 -1.06121674e-01
  1.44238383e-01 -1.40302911e-01 -2.09854200e-01  1.64098702e-02
 -1.18558832e-01  6.73992336e-02 -1.43178713e+00  2.22866207e-01
  2.38166600e-01 -1.44933152e+00  1.27820268e-01  2.87657768e-01
 -9.61351618e-02 -2.96283752e-01  1.36419728e-01 -5.24698421e-02
  2.42304936e-01  2.25802854e-01 -2.14182958e-01 -4.49791588e-02
 -6.94605038e-02 -1.99323595e-01 -4.17601410e-03  1.10292554e-01
  3.10080647e-01 -1.76273212e-01 -9.64487717e-02  3.53460401e-01
  1.93873998e-02 -1.53844535e+00  4.16674435e-01  1.59251645e-01
  6.26037791e-02  7.62917250e-02  2.19637647e-01 -2.52944052e-01
  2.44970873e-01 -3.05033386e-01  2.30659291e-01  1.25759155e-01
 -2.50818044e-01 -1.69090182e-01 -6.11315630e-02 -4.38177139e-01
 -1.81091391e-02  4.80638713e-01 -6.86462000e-02 -3.63419622e-01
 -1.12174824e-01 -2.14653332e-02 -1.27548337e-01 -1.24175653e-01
  3.23008932e-02 -7.76418522e-02 -3.39805126e-01  5.72347268e-02
  2.71597773e-01 -1.26186264e+00 -1.78162372e+00  1.14846897e+00
 -1.07884578e-01  5.90159707e-02  1.91374302e-01  2.16208696e+00
 -1.26967989e-02  2.66510248e-01 -2.33091488e-01  1.64231926e-01
 -5.71067352e-03  3.11281824e+00  3.83423477e-01  1.11873969e-02
  1.69720650e+00 -2.30994970e-02  4.51492041e-01 -2.95374274e-01
 -1.79214191e+00 -1.98367918e+00 -2.43604034e-01 -1.03978645e-02
  8.00510347e-02  2.78166294e-01  3.03651206e-02 -2.97861040e-01
  2.89414167e-01 -2.03860745e-01  1.16701074e-01 -6.86645135e-02
  2.79511064e-02 -2.13887632e-01 -1.40069604e-01 -1.84739858e-01
  9.69423875e-02  2.57612646e-01  7.29377210e-01  2.37638399e-01
  1.72332227e-01 -1.29835442e-01 -1.20996550e-01 -1.93945575e+00
  3.37712973e-01  1.95855685e-02  2.50728160e-01 -9.99579579e-02
  2.93843765e-02  1.80014536e-01 -6.65037408e-02 -3.20121080e-01
  1.28087208e-01 -9.49946418e-02  2.63097465e-01 -1.11401550e-01
 -9.39967334e-02 -1.05436757e-01  3.23900998e-01  7.51027465e-03
 -1.15304179e-01  1.93583846e+00  2.91775838e-02 -2.69687116e-01
  1.57934725e-01  2.40568578e-01  5.77526629e-01 -9.28429216e-02
  1.06260382e-01 -1.35665312e-01 -2.67999452e-02  2.29170606e-01
 -8.56261030e-02  3.06244586e-02 -2.18930334e-01  5.84103959e-03
 -2.99708974e-02 -6.27243072e-02  5.73353171e-01  8.17376077e-02
 -2.34542176e-01 -7.14749277e-01 -1.41329780e-01  1.52388453e-01
  9.28550307e-03 -6.39113178e-03 -9.19613391e-02  4.57731374e-02
  1.01182185e-01  1.26938194e-01 -4.93564941e-02 -1.54991150e-01
 -1.75834056e-02 -1.44480363e-01 -4.70929533e-01 -3.58390838e-01
 -2.02105373e-01 -1.13372961e-02 -3.54229391e-01 -4.49086159e-01
 -9.57821906e-02  1.67638230e+00  1.37459487e-01 -4.65940274e-02
  9.73795831e-01  9.98361409e-02 -6.83190813e-03  2.74083883e-01
  5.97984865e-02  1.80264279e-01  5.05496515e-03 -1.94956437e-01
  2.35208616e-01  2.85958737e-01  1.63971737e-01 -2.35296562e-01
 -1.63439184e-01  2.59350777e-01  2.81333387e-01  3.68334949e-01
 -1.98557302e-02  1.52960077e-01 -6.65893480e-02 -3.88746530e-01
  1.20797217e-01  3.67548503e-02  2.76561379e-01 -1.70875818e-01
  4.12687175e-02  7.81503692e-02  9.98661295e-02  2.79230028e-02
 -1.24930419e-01  1.23286761e-01 -1.71929121e-01  7.26467818e-02
  2.26797357e-01  1.13720410e-01  3.03458810e-01  1.56712681e-01
  4.90145423e-02  2.18455359e-01 -2.55560666e-01 -5.66886328e-02
 -2.55473346e-01  3.67030889e-01  1.77097321e-02 -1.46048322e-01
  2.19867274e-01 -4.19788122e-01  1.69741020e-01 -1.58182353e-01
 -5.50196469e-01  5.87768257e-02 -3.08982972e-02 -1.34694576e-01
 -6.12642504e-02 -2.88411289e-01 -2.55372941e-01  1.11737777e-03
  6.92875907e-02 -5.65595366e-02  2.56909341e-01  7.34550804e-02
  2.36829042e-01  2.38548502e-01 -6.14774302e-02 -1.76211759e-01
  3.71557958e-02  5.90903349e-02 -1.35005079e-02 -4.55051735e-02
 -1.35346040e-01 -1.26515791e-01  1.72953174e-01 -5.77941686e-02
 -5.79486415e-03  2.18497172e-01  1.51488543e-01  3.35749924e-01
 -1.70952991e-01  1.54947266e-01  9.74947587e-02 -2.20758486e+00
 -1.06349394e-01 -1.90985929e-02  1.98549286e-01  7.73901343e-02
  2.52709508e-01  8.02258253e-01  1.77804947e-01 -1.97782502e-01
 -3.03155780e-01 -1.18117161e-01 -1.79238603e-01 -1.77067235e-01
  5.24009531e-03 -8.06138217e-01  1.40020907e-01 -1.48715809e-01
  7.41804093e-02 -4.33164895e-01 -1.02226704e-01 -1.63282049e+00
 -2.45546624e-01 -2.56286025e-01 -1.66886095e-02 -3.08348387e-01
 -2.47855559e-01 -1.42180204e-01 -4.30892080e-01 -8.05380717e-02
  1.97330236e-01 -1.75008014e-01  7.84870889e-03  1.75681755e-01
 -1.55684471e-01  3.58048350e-01  2.80789077e-01 -5.62653579e-02
 -1.65343449e-01  3.95472646e-02  1.29793301e-01  4.99127023e-02
 -2.79424842e-02 -4.38274950e-01  3.89196761e-02  5.30330479e-01
  2.07386285e-01  6.88041225e-02  8.67322534e-02 -2.84923673e-01
  3.15719210e-02 -1.59506857e+00  9.78160501e-02 -1.11275367e-01
  1.21356489e-03 -1.20903902e-01  1.25882894e-01 -8.32597837e-02
 -1.13871560e-01 -1.78258806e-01 -8.41136873e-02 -5.39364636e-01
  1.18525594e-01  1.78685933e-02  4.12812173e-01  1.24286219e-01
  1.94901675e-01  2.12799773e-01  1.27727076e-01 -4.32119340e-01
 -6.36291951e-02  1.10811837e-01 -1.68012217e-01  2.99636483e-01
  3.14586237e-02 -7.59182274e-02  3.85273695e-01  3.10000241e-01
  1.21370375e-01 -2.27057710e-01  7.61091411e-02  1.57910660e-01
 -1.15488815e+00  7.92813227e-02  7.80960917e-02 -1.13603778e-01
  1.83178380e-01 -2.53208160e-01  3.21625769e-01  2.67482772e-02
  4.39891279e-01 -1.11203725e-02  4.78849500e-01  1.69959104e+00
  1.16889104e-01  1.26612782e-01  1.09278210e-01 -3.29262507e-03
 -3.04535419e-01  1.62098259e-01 -3.46022069e-01  1.81968999e+00
 -9.15733129e-02  1.17228674e-02  7.57245123e-02  3.06145042e-01
  1.25133619e-01  1.50315487e+00  6.57578632e-02  4.07316238e-02
  1.40984327e-01 -3.88532989e-02  4.29447740e-02  1.86044082e-01
 -6.88072965e-02 -7.37234205e-02  1.24714367e-01 -1.14731705e+00
 -1.22025982e-01  3.25984001e-01  2.72327095e-01  3.39770652e-02
 -7.81973779e-01  2.87428409e-01  2.63117440e-02 -7.45636672e-02
 -2.05166101e-01  3.13901603e-01 -2.38593876e-01  5.90124354e-02
  1.87551722e-01  1.16732530e-01  1.52826726e-01  3.43410045e-01
  1.81479022e-01  1.43768698e-01  2.89805740e-01 -3.33262265e-01
  2.30629012e-01 -1.82597116e-01 -1.14888344e-02  8.24788928e-01
 -4.06038985e-02 -1.45873368e-01  1.68729916e-01 -3.37815940e-01
 -4.56495911e-01 -3.09576213e-01  3.98970097e-01  2.39685521e-01
  3.80632877e-01  7.09939795e-03  1.51291206e-01  1.46297187e-01]
(768,)

In [127]:
import pandas as pd

df_vetorizado = pd.DataFrame(X_embeddings)

df_vetorizado.to_excel("vetorizacao_distilbert.xlsx", index=False)

In [128]:
from google.colab import files

files.download("vetorizacao_distilbert.xlsx")